### ISSUE TITLE
automatic generation boolean

### ISSUE THREAD

**Issue by SirGram** [Language-Tools/anki-hyper-tts#97] opened 2023-03-10 23:43 UTC
Would it be possible to add the audio automatically when creating a flashcard instead of having to push the "add audio" button?

**Comment by luc-languagetools** [comment] 2023-03-11 06:16
This is planned and coming very soon

**Comment by luc-languagetools** [comment] 2023-08-28 23:13
see #84

**Comment by luc-languagetools** [comment] 2023-11-09 23:12
closing as duplicate of #84

**Closed by luc-languagetools** 2023-11-09 23:12 UTC
